# =============================================================================
# Deploy Preview Workflow - Déploiement de Preview
# =============================================================================
# Déclenché sur: pull requests
# Actions: build, deploy preview, commentaire PR
# =============================================================================

name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '9'

jobs:
  # ===========================================================================
  # Build & Deploy Preview
  # ===========================================================================
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
        env:
          # Variables d'environnement pour le build preview
          NEXT_PUBLIC_ENV: preview
          VITE_ENV: preview

      # =========================================================================
      # Option A: Vercel
      # =========================================================================
      # - name: Deploy to Vercel
      #   id: vercel
      #   uses: amondnet/vercel-action@v25
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      #     scope: ${{ secrets.VERCEL_ORG_ID }}

      # =========================================================================
      # Option B: Netlify
      # =========================================================================
      # - name: Deploy to Netlify
      #   id: netlify
      #   uses: nwtgck/actions-netlify@v3
      #   with:
      #     publish-dir: './dist'
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     deploy-message: "PR #${{ github.event.pull_request.number }}"
      #     enable-pull-request-comment: true
      #     enable-commit-comment: false
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # =========================================================================
      # Option C: Cloudflare Pages
      # =========================================================================
      # - name: Deploy to Cloudflare Pages
      #   id: cloudflare
      #   uses: cloudflare/pages-action@v1
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     projectName: your-project-name
      #     directory: dist
      #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      # =========================================================================
      # Option D: GitHub Pages (pour démo)
      # =========================================================================
      - name: Deploy to GitHub Pages Preview
        id: deploy
        run: |
          # Simuler un déploiement pour la démo
          echo "preview_url=https://preview-pr-${{ github.event.pull_request.number }}.example.com" >> $GITHUB_OUTPUT
          echo "Deployment simulated - configure your actual deployment above"

      # =========================================================================
      # Commentaire sur la PR
      # =========================================================================
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = '${{ steps.deploy.outputs.preview_url }}';

            const body = `## 🚀 Preview Deployment

            | Status | URL |
            |--------|-----|
            | ✅ Deployed | [Preview Link](${previewUrl}) |

            ### Commit
            \`${{ github.event.pull_request.head.sha }}\`

            ---
            <sub>Deployed by GitHub Actions</sub>`;

            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('Preview Deployment')
            );

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }

  # ===========================================================================
  # Lighthouse Audit (optionnel)
  # ===========================================================================
  lighthouse:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    needs: deploy-preview
    if: false # Activer si preview URL disponible
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            ${{ needs.deploy-preview.outputs.preview_url }}
          uploadArtifacts: true
          temporaryPublicStorage: true
